create table "public"."type" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."type" enable row level security;

create type relation_type AS ENUM ('double', 'half', 'zero');

create table "public"."type_relation" (
    "type1" bigint not null,
    "type2" bigint not null,
    "relation_type" relation_type not null
);


alter table "public"."type_relation" enable row level security;

CREATE UNIQUE INDEX type_name_key ON public.type USING btree (name);

CREATE UNIQUE INDEX type_pkey ON public.type USING btree (id);

CREATE UNIQUE INDEX type_relation_pkey ON public.type_relation USING btree (type1, type2, relation_type);

alter table "public"."type" add constraint "type_pkey" PRIMARY KEY using index "type_pkey";

alter table "public"."type_relation" add constraint "type_relation_pkey" PRIMARY KEY using index "type_relation_pkey";

alter table "public"."type" add constraint "type_name_key" UNIQUE using index "type_name_key";

alter table "public"."type_relation" add constraint "public_type_relation_type1_fkey" FOREIGN KEY (type1) REFERENCES public.type(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."type_relation" validate constraint "public_type_relation_type1_fkey";

alter table "public"."type_relation" add constraint "public_type_relation_type2_fkey" FOREIGN KEY (type2) REFERENCES public.type(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."type_relation" validate constraint "public_type_relation_type2_fkey";


