create schema if not exists "pokeapi";

create table "pokeapi"."egg_group" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "pokeapi"."egg_group" enable row level security;

CREATE UNIQUE INDEX egg_group_name_key ON pokeapi.egg_group USING btree (name);

CREATE UNIQUE INDEX egg_group_pkey ON pokeapi.egg_group USING btree (id);

alter table "pokeapi"."egg_group" add constraint "egg_group_pkey" PRIMARY KEY using index "egg_group_pkey";

alter table "pokeapi"."egg_group" add constraint "egg_group_name_key" UNIQUE using index "egg_group_name_key";


