create table "public"."egg_group" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."egg_group" enable row level security;

CREATE UNIQUE INDEX egg_group_name_key ON public.egg_group USING btree (name);

CREATE UNIQUE INDEX egg_group_pkey ON public.egg_group USING btree (id);

alter table "public"."egg_group" add constraint "egg_group_pkey" PRIMARY KEY using index "egg_group_pkey";

alter table "public"."egg_group" add constraint "egg_group_name_key" UNIQUE using index "egg_group_name_key";

alter table "egg_group" enable row level security;

create policy "allow authenicated users to select for egg_group" on egg_group for
select
  to authenticated using (true);

create policy "allow anonymous to select for egg_group" on egg_group for
select
  to anon using (true);